SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
EXP_NAME: 'DirectJoint'
TRAIN:
  INPUT_SIZE_TARGET: [1024, 512]
  BATCH_SIZE_TARGET: 1
  BATCH_SIZE_SOURCE: 1
  DA_METHOD: DirectJoint
  MODEL: FCN8s
  OPTIMIZER: 'Adam'
  SCHEDULER: 'polynomial'
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MAX_ITERS: 150000
  EARLY_STOP: 150000
TEST:
  INPUT_SIZE_TARGET: [1024, 512]
  OUTPUT_SIZE_TARGET: [1024, 512]
  MODE: best
  MODEL:
    - FCN8s
  SNAPSHOT_MAXITER: 150000
