SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
EXP_NAME: 'TargetOnly'
TRAIN:
  INPUT_SIZE_TARGET: [512, 256]
  DA_METHOD: TargetOnly
  MODEL: FCN8s
  OPTIMIZER: 'SGD'
  SCHEDULER: 'step'
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MAX_ITERS: 150000
  EARLY_STOP: 150000
TEST:
  INPUT_SIZE_TARGET: [512, 256]
  OUTPUT_SIZE_TARGET: [512, 256]
  MODE: best
  MODEL:
    - FCN8s
  SNAPSHOT_MAXITER: 150000
