SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
EXP_NAME: 'train_FCN_with_W'
TRAIN:
  INPUT_SIZE_TARGET: [1024, 512]
  BATCH_SIZE_TARGET: 1
  BATCH_SIZE_SOURCE: 1
  DA_METHOD: 'train_FCN_with_W'
  MODEL: FCN8s
  MODEL_PATH: '/home/yiren/META_DOMAIN_TRANSFER/pretrained_models/GTA2CityScapes_gen3.pth'
  MODEL_W_PATH: '/home/yiren/META_DOMAIN_TRANSFER/pretrained_models/GTA2CityScapes_W_gen3.pth'
  OPTIMIZER: 'Adam'
  SCHEDULER: 'polynomial'
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MAX_ITERS: 15000
  EARLY_STOP: 15000
  SAVE_PRED_EVERY: 500
TEST:
  INPUT_SIZE_TARGET: [1024, 512]
  OUTPUT_SIZE_TARGET: [1024, 512]
  MODE: best
  MODEL:
    - FCN8s
  SNAPSHOT_MAXITER: 15000
  SNAPSHOT_STEP: 500
