SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
EXP_NAME: 'train_W_with_FCN'
TRAIN:
  INPUT_SIZE_TARGET: [1024, 512]
  DA_METHOD: 'train_W_with_FCN'
  MODEL: FCN8s
  OPTIMIZER: 'Adam'
  SCHEDULER: 'polynomial'
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MAX_ITERS: 10000
  EARLY_STOP: 10000
  META_LEARNING_RATE: 0.0001
  META_WEIGHT_DECAY: 0.0001
  SAVE_PRED_EVERY: 200
