SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
EXP_NAME: 'train_W_with_FCN'
TRAIN:
  INPUT_SIZE_TARGET: [1024, 512]
  BATCH_SIZE_TARGET: 1
  BATCH_SIZE_SOURCE: 1
  DA_METHOD: 'train_W_with_FCN'
  MODEL_PATH: '/home/yiren/META_DOMAIN_TRANSFER/pretrained_models/GTA2CityScapes_gen3.pth'
  MODEL_W_PATH: '/home/yiren/META_DOMAIN_TRANSFER/pretrained_models/GTA2CityScapes_W_gen3.pth'
  MODEL: FCN8s
  OPTIMIZER: 'Adam'
  SCHEDULER: 'polynomial'
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MAX_ITERS: 10000
  EARLY_STOP: 10000
  META_LEARNING_RATE: 0.0001
  META_WEIGHT_DECAY: 0.0001
  SAVE_PRED_EVERY: 200
